filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/*.log
    - /var/log/suricata/*.log
    - /var/log/workstation1/*.log
    - /var/log/workstation2/*.log

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  protocol: "http"
  username: "elastic"
  password: "changeme"
